### ISSUE TITLE
Intermittent email failures

### ISSUE THREAD

**Issue by lesley-w** [PerplexDigital/PerplexMail-for-Umbraco#8] opened 2020-09-16 00:02 UTC
We are getting intermittent email failures with one or other of the following errors:

- The operation has timed out.
- Failure sending mail.; Unable to read data from the transport connection: net_io_connectionclosed.

There doesn't seem to be a pattern of when an email will succeed or fail, and using "Resend" from the Umbraco back-office is successful.

Some suggestions I have found online are: 

- SmtpClient should be accessed within a "Using" statement to ensure that "QUIT" is sent to the server to close the connection
- Catch the error and retry

But both of these would require updating the PerplexMail code.

Just wondering if other users have had the same issue, and if you know of a solution.

**Comment by PerplexWouter** [comment] 2020-09-18 16:01
Hello,

I just checked the code and you are correct, and I'm actually surprised to find, that the SmtpClient is not being disposed of properly. I have never really heard anyone report on this issue before though, so I am not sure if it is really the cause of your issues (especially since it appears to be intermittent). As the PerplexMail.Mail class is currently not disposable I think calling .Dispose() on the SmtpClient would have to take place right after the e-mail has been sent.

Unfortunately I don't have the time to make changes to this project myself, however if you are willing to make a PR I'm more than happy to check it out and pull it into the main branch.

[I believe we could dispose the SmtpClient right after this line of code, before returning the result.](https://github.com/PerplexDigital/PerplexMail-for-Umbraco/blob/2dffbc46d57879785cf2ce3cb305459eb24b621b/PerplexMail/Email.cs#L1004)

As for the retry-strategy: the Mail class is really intended to be a one-shot service, and I believe just doing a retry on any error really doesn't serve much purpose as in almost all cases the Mail will fail to send the second time around as well. Plus I believe the retry-strategy should really be in the hands of the developer using the package. For example, depending on the importance of the e-mails, a double-backing strategy is a common strategy for such cases, but that would fall well out of the scope of what this package is intended to give as a service.

What I would recommend in your case is to not use the static method PerplexMail.Mail.SendMail(...) but instead use the static method PerplexMail.Mail.CreateUmbracoEmail(...) to create the email instead and then sending it afterwards. This would allow you to try sending it a second time, like this:
 
``` c# 
var mail = PerplexMail.Mail.CreateUmbracoEmail(nodeId, tags, attachments);
try
{  
    mail.SendEmail();
} catch (SmtpException)
{
  // Determine retry-strategy
    mail.SendEmail();
}
```

Let me know if this solution works for you!

**Comment by lesley-w** [comment] 2020-10-16 01:52
Hi Wouter,
I have finally got around to creating a PR for this. 

Hopefully I've done it right!

**Comment by PerplexWouter** [comment] 2020-10-16 12:45
Hi,

Yes the changes were fine, I've already pulled in your changes! I've decided to clean up the repository a bit, but I have compiled the DLL, with a new version number, and placed it in the repository under the /output/ folder. Or you can just clone the solution and build it :) I hope this will solve your issues for now.

I will close this issue but if you still have more questions or you still have problems feel free to reply here.

**Closed as completed by PerplexWouter** 2020-10-16 12:45 UTC
